# These are supported funding model platforms

github:
  - ResolveErrorStack

# patreon:
#   - your-patreon-name

# open_collective:
#   - your-open-collective-name

# ko_fi:
#   - your-kofi-name

# tidelift:
#   - npm/babel

# community_bridge:
#   - your-project-name

# liberapay:
#   - your-liberapay-name

# issuehunt:
#   - your-issuehunt-name

# otechie:
#   - your-otechie-name

# custom:
#   - https://your-custom-support-link.com
